name: auto-publish

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: python -m pip install --upgrade pip baku
      - name: Build blog
        run: |
          baku --build
          TEMP=`mktemp -d`
          cp -r html/* $TEMP
          git checkout gh-pages
          rm -rf *
          cp -r $TEMP/* ./
          touch .nojekyll
          ls

# TODO: commit & push to gh-pages
